### ISSUE TITLE
Decrypting from stored protocol buffer file fails

### ISSUE THREAD

**Issue by mpost** [osipxd/encrypted-datastore#10] opened 2022-12-01 09:30 UTC
After writing a protobuf file and reopening the app, reading the encrypted file fails with the following exception:

``` java
  Caused by: java.io.IOException: No matching key found for the ciphertext in the stream.
                 	at com.google.crypto.tink.streamingaead.InputStreamDecrypter.read(InputStreamDecrypter.java:176)
                 	at com.google.protobuf.CodedInputStream$StreamDecoder.read(CodedInputStream.java:2080)
                 	at com.google.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2831)
                 	at com.google.protobuf.CodedInputStream$StreamDecoder.isAtEnd(CodedInputStream.java:2754)
                 	at com.google.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2107)
                 	at com.google.protobuf.CodedInputStreamReader.getFieldNumber(CodedInputStreamReader.java:82)
                 	at com.google.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3913)
                 	at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3895)
                 	at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1647)
```

I am using `v1.0.0-alpha03` of the library.

Among other cases this type of error occurs when the outputstream the file is written to is not closed. This can be observed when using the regular `EncryptedFile` and not closing its outpur stream after write. Loading the file again fails with the same exception.

However looking at the datastore implementation... they make use if the `file.use { ... }` function which would indicate a close operation. Feedback is appreciated.

**Comment by osipxd** [comment] 2022-12-01 10:07
Thanks you for report! Can you provide snippet to reprodcue this behavior? It would be helpful

**Comment by mpost** [comment] 2022-12-01 11:24
Here are the bits to recreate the the scenario:

## Dependencies:

``` kotlin
implementation("io.github.osipxd:security-crypto-datastore:1.0.0-alpha03")
implementation("com.google.protobuf:protobuf-javalite:3.21.9")
```
## Protobuf config:
```kotlin

plugins {
    id("com.google.protobuf") version "0.9.1"
}

...
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.21.9"
    }
    generateProtoTasks {
        all().forEach {
            it.builtins {
                id("java") {
                    option("lite")
                }
            }
        }
    }
}
```

## Encrypted Datastore 

``` kotlin
val dataStore = DataStoreFactory.createEncrypted(serializer) {
    EncryptedFile.Builder(
        context.dataStoreFile("filename.pb"),
        context,
        MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC),
        EncryptedFile.FileEncryptionScheme.AES256_GCM_HKDF_4KB
    ).build()
}
```

##The protocol buffer serializer:

``` kotlin
import androidx.datastore.core.CorruptionException
import androidx.datastore.core.Serializer
import com.google.protobuf.InvalidProtocolBufferException
import java.io.InputStream
import java.io.OutputStream

object AppDataSerializer : Serializer<AppData> {

    override val defaultValue: AppData = AppData.getDefaultInstance()

    override suspend fun readFrom(input: InputStream): AppData {
        try {
            return AppData.parseFrom(input)
        } catch (exception: InvalidProtocolBufferException) {
            throw CorruptionException("Can not read AppData proto", exception)
        }
    }

    override suspend fun writeTo(t: AppData, output: OutputStream) = t.writeTo(output)

}
```

## Usage

Now writing something to the store and reading it after app process has been kill (app reinstalled) throws the above exception.

**Comment by osipxd** [comment] 2022-12-01 13:45
Thank you, I'll try to reproduce it at weekend

**Comment by mpost** [comment] 2022-12-02 15:36
Quick update this issue is not protobuf specific it also happens when serlializing to json with kotlinx serialization.

**Comment by osipxd** [comment] 2022-12-06 09:44
@mpost Sorry, this task delayed a bit, but I'll return to it ASAP

**Comment by mpost** [comment] 2022-12-16 15:45
I have recreated a the issue in a minimal snippet: [encrypted-sandbox.zip](https://github.com/osipxd/encrypted-datastore/files/10247056/encrypted-sandbox.zip).

Hope this helps to recreate the issue. Store data. Kill and restart the app:

``` java
Caused by: java.io.IOException: No matching key found for the ciphertext in the stream.
at com.google.crypto.tink.streamingaead.InputStreamDecrypter.read(InputStreamDecrypter.java:176)
```

The snippet serializes to string.

```
object StringSerializer : Serializer<String> {

    override val defaultValue: String = ""

    override suspend fun readFrom(input: InputStream): String {
        try {
            return input.reader().readText()
        } catch (exception: Exception) {
            throw CorruptionException("Can not read string", exception)
        }
    }

    override suspend fun writeTo(t: String, output: OutputStream) =
        output.writer().write(t)

}
```
the datastore
```
        val dataStore = DataStoreFactory.createEncrypted(StringSerializer) {
            EncryptedFile.Builder(
                dataStoreFile("filename"),
                this,
                MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC),
                EncryptedFile.FileEncryptionScheme.AES256_GCM_HKDF_4KB
            ).build()
        }
```
It doesn't get much simpler.

**Comment by krzdabrowski** [comment] 2022-12-19 13:37
I confirm the bug and can be reproduced even simpler - applies to `security-crypto-datastore-preferences` as well. Everything works fine during first app launch (multiple write as well) but when you restart your app, the crash occurs.

Minimum reproducible scenario:
`implementation("io.github.osipxd:security-crypto-datastore-preferences:1.0.0-alpha03")`

Then in `MainActivity`:
```
class MainActivity : AppCompatActivity() {
    val dataStore by lazy {
        PreferenceDataStoreFactory.createEncrypted(
            encryptionOptions = { }
        ) {
            EncryptedFile.Builder(
                // The file should have extension .preferences_pb
                dataStoreFile("filename.preferences_pb"),
                this,
                MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC),
                EncryptedFile.FileEncryptionScheme.AES256_GCM_HKDF_4KB
            ).build()
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    override fun onStart() {
        super.onStart()
        val stringPreferencesKey = stringPreferencesKey("testKey")

        GlobalScope.launch {
            dataStore.edit {
                it[stringPreferencesKey] = "testValue"
            }
        }
    }
}
```

**Comment by osipxd** [comment] 2022-12-19 18:36
@mpost, @krzdabrowski, thank you both for examples. Reproduced!
Looks like the issue occurs because output stream is not closed. For example in the `StringSerializer` to fix the issue you can modify `writeTo` like this:
```diff
override suspend fun writeTo(t: String, output: OutputStream) =
-        output.writer().write(t)
+        output.writer().use { it.write(t) }
```

But in the case you use `PreferenceDataStore` it is not possible to close output stream manually, so I'll add stream closing on the library side.

**Closed** 2022-12-19 19:30 UTC
Labels: bug

**Comment by mpost** [comment] 2022-12-20 09:53
@osipxd I also saw the UnclosableStream when looking into the issue. They don't close because of the `stream.fd.sync()` they do afterwards. I am not sure if that would also work on a closed stream. However the closing you apply now manually does resolve the issue as expected. That is great. 👍 Hopefully that does not interfere with the sync(). Thanks for looking into it.

**Comment by mpost** [comment] 2022-12-20 10:55
Ah ok, That is good to know 👍
